AllCops:
  TargetRubyVersion: 2.5

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 190

Metrics/ModuleLength:
  Max: 175
  Exclude:
    - 'lib/skull_island/helpers/resource.rb'

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/skull_island/cli.rb'

Metrics/AbcSize:
  Max: 28

Metrics/BlockLength:
  Max: 35
  Exclude:
    - '*.gemspec'
    - Rakefile
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'

Layout/HeredocIndentation:
  Enabled: false

Security/Eval:
  Exclude:
    - 'lib/skull_island/cli.rb'

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*_spec.rb'
