require:
- rubocop-rake
- rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/MethodLength:
  Max: 50

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 100

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'

Lint/MissingSuper:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 175
  Exclude:
    - 'lib/skull_island/helpers/resource.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'lib/skull_island/cli.rb'

Metrics/AbcSize:
  Max: 28

Metrics/BlockLength:
  Max: 35
  Exclude:
    - '*.gemspec'
    - Rakefile
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'

Layout/HeredocIndentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Security/Eval:
  Exclude:
    - 'lib/skull_island/cli.rb'

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/OptionalBooleanParameter:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true
