env:
  global:
    secure: X0rMm9ggYBmo9qLM7D5UYrEa1EpKQV+OzXsHKmHFnZteAlc4EUOsuT0EfYSP+zWUJVUjjSb69CYz70slYxnc8Ovoya/k790mve/aPiJCjq7CFXdZDyMALFttBshcVO5sAGhvkyvD/vtUMiaiZNEQheHJ6P3DnAOYCTEcFKxRfmauzYmFuIUuDZXKDfvIar1TgWguOxk52jXkks68n8iS0UzRyMTgrA0+VxCWpmzGAuuKATcYmt/vuSjeNY1DoLHPuhrhtDHtbL0U0qNkaFauzjr+p8GOcNGEh38sY/+rBLTIEoQifmtkvM0UjKkJJHYwG+5TiCKAtqeVtqyP1mNhDdbuQtprzuzt/AvFevcy2g1KsjEGXn4mklahyDsBWiCOGAmlik/HmUnTCfy1daJLajWcy6JLg6GcNxMzufPVWDe/ceWp6J3Wd7JVhJ96d7qo5hufTnOSpLr/vtVuZ3ZRaPfYHRxhardwaWA2szW1J7/rVKPJn1/jQ8xu3+9eqKJa7IT8sPIDBHAyFo+W5rLUMeicXRKAcVGeCO6rs/auGWnD2/xXO830T0GiYU6AohEeY/w5vBVvuKLbbJvHWH71EiPHTykAL0pIFOlCC4m7kxwsfA+GvYAboWxTdUNc53Vgz8/1lomRBqaf/q7c2lFjW4MIgfLGDxnzGbaf8cVEVDg=
language: ruby
cache: bundler
rvm:
- 3.1
before_install: gem install bundler -v '~> 2.2'
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter format-coverage -t cobertura coverage/coverage.xml"
- "./cc-test-reporter upload-coverage"
- exit $TRAVIS_TEST_RESULT
deploy:
  provider: rubygems
  api_key:
    secure: Gj3+sg3iSZytx7vNsnu6U/I61BVwz2rFB3WoclMoFuqdWwUyK/4qd2wC0OIvQQJg6Ex1nBwws6VjHUUOCtRiUIF62yR7pDE/ITHkzjjEtZ/ru/6ZKkyHmpenV6Pu0TzENgEY7EIu7pGOJr/57INUuuq7bZM0qV5Rew6Feg2t9n3o8hAONS614MB64Ig6PHRSiGUkm9iogaksQodeb2RvHrQgCXNnhAxq/TdU0TPV7DDDtx4piM1hpdm4sMwznCqZKC89WV7WajeWhQJdaXoGWxDq2ZmF3gM5q8cnK5Uh5wf2pKWce3N8ikeOuiLe06RLQ2pH7UBU9ku9u3+naqFjDZb3d/2DRoxZFjy/P6CRinfoOrsR0k74pc5lnsyQlkxJsJILoOLz7hV4oi9MBi8tDafGz6XVi+UMGE34Nj/7oZjvnbmIuYRJSC+7564y7tsPykOXuCOV6BuDUclXLxTbaLUTLCRcbDluzNrxymbxs3KSZBfM6jli66oXroagaYCdL5zPiGDD5W0crv0c6eDRQAuDOTUllQy/75FRGFn5hbomHQBVM18pm9sx/k6AB+thanIcottdRKst6xh/EN3KnQsLV1M2hSq3gG8EyoqObkIhvcOtCKqfG5VId8qOxT01UcaKui4exyqAv8LAW0WCAL1kyl6Oty1ArZao5fibGUI=
  gem: skull_island
  on:
    tags: true
    rvm: 3.1
    repo: jgnagy/skull_island
